### ISSUE TITLE
When mocking indirectly require'd modules, the non-mocked version is used

### ISSUE THREAD

**Issue by jalfd** [testdouble/quibble#105]
If you have three modules A, B and C, where A is required by B and B is required by C, quibble fails in the following scenario:

1. require module B (It will be loaded normally, and cached. The module will hold a reference to A, which is also loaded and cached)
2. quibble module A
3. require module C

We would expect module C to hold a reference to B which holds a reference to the quibbled module A. Instead, we get the original unquibbled version of A.

This happens because, when C invokes the quibble loader to load B, it finds that B is not quibbled, and so it delegates to the normal loader, which returns the already cached version, which references the non-quibbled version of A.

The correct behavior would be, when loading B, to detect that it has a dependency on A, which is now quibbled, and therefore return a new version of B. Of course that may be easier said than done. :)

**Comment by jalfd** [comment]
I've created a PR adding a test case for this issue: https://github.com/testdouble/quibble/issues/105

Note, I haven't looked at whether the same problem occurs with ESM modules

**Comment by searls** [comment]
Quibbling isn't quantum: if you require B and then quibble A, the library does not perform any kind of static analysis to go back retroactively and uncache B such that it gets the quibbled version of A. 

Additionally, quibbling transitive dependencies isn't supported in quibble (by design). See the conversation here: https://github.com/testdouble/testdouble.js/issues/379
